# Site settings

baseurl: / # the subpath of your site, e.g. /blog/

permalink: /:categories/:title.html

encoding: utf-8

title: Chuanjiang Li's Blog | @lamChuanJiang

description: > # this means to ignore newlines until "baseurl:"

 1. Quiter you be, more you hear.
 
 2. Keep it simple, stupid, but serviceable.

 @lamChuanJiang.

url: "http://lamchuanjiang.github.io" # the base hostname & protocol for your site

author: Chuanjiang Li

id: lamChuanJiang

email: lamchuanjiang@gmail.com

# Build settings

# markdown engine list
markdown: rdiscount
# markdown: redcarpet
# markdown: kramdown

# old version jekyll use pygments:true
# pygments: true

# if GitHub then pygments
highlighter: pygments

# if Jekyll 3.0
#highlighter: pigments
#excerpt_separator: ""  

# if local test then rouge that can avoid pygments and python installing
#highlighter: rouge

# if Jekyll 3.0+, then use: "gems: [jekyll-paginate]" to include jekyll-paginate
# But make sure that the gem "jekyll-paginate " has been installed

gems: [jekyll-paginate]
paginate: 5
paginate_path: "/home/paginate_:num"

production_url : http://lamchuanjiang.github.io

#exclude: ["css", "image", "js", "fonts"]
