# Site settings

baseurl: / # the subpath of your site, e.g. /blog/

permalink: /:categories/:title.html

encoding: utf-8

title: Chuanjiang Li's Blog | @ckwongloy

description: > # this means to ignore newlines until "baseurl:"

 1. Quiter you be, more you hear.
 
 2. Keep it simple, stupid, but serviceable.

 @ckwongloy.

url: "http://ckwongloy.github.io" # the base hostname & protocol for your site

author: Chuanjiang Li

id: ckwongloy

email: ckwongloy@gmail.com

# Build settings

# markdown engine list
#markdown: rdiscount
# markdown: redcarpet
markdown: kramdown

# old version jekyll use pygments:true
# pygments: true

# if GitHub then pygments
#highlighter: pygments

# if Jekyll 3.0
#highlighter: pigments
#excerpt_separator: ""

# if Jekyll 3.0 on GitHub or local test then rouge that can avoid pygments and python installing
highlighter: rouge

# if Jekyll 3.0+, then use: "gems: [jekyll-paginate]" to include jekyll-paginate
# But make sure that the gem "jekyll-paginate " has been installed

gems: [jekyll-paginate]
paginate: 5
paginate_path: "/home/paginate_:num"

production_url : http://ckwongloy.github.io

#exclude: ["css", "image", "js", "fonts"]
